# Generated by Django 4.2.5 on 2023-09-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='names')),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_schedule', models.TimeField(auto_created=True)),
                ('date_schedule', models.DateField(auto_created=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.patient')),
            ],
        ),
    ]
